load sense_amp_balanced_widest
save sense_amp_balanced_widest_routed_hier
flatten sense_amp_balanced_widest_flat
load sense_amp_balanced_widest_flat
drc check
drc count total
save sense_amp_balanced_widest_flat
quit -noprompt
